<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Uniuyo Dues</title>
<meta name="description" content="">
<meta name="author" content="">
<!-- Bootstrap -->
<link rel="stylesheet" type="text/css"  href="css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="fonts/font-awesome/css/font-awesome.css">

<!-- Stylesheet
    ================================================== -->
<link rel="stylesheet" type="text/css"  href="css/style.css">

</head>
<body>
<!-- Header -->
<header id="header">
  <div class="intro">
    <div class="overlay">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-8">
            <div class="intro-text">
              <h1>UNIUYODUES.COM</h1>
              <p>Dues Payment Portal </p>
              <a href="Register.PHP" class="btn btn-custom btn-lg page-scroll">Register</a> <a href="login.php" class="btn btn-custom btn-lg page-scroll">Login</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
</body>
</html>
